added project working
Pradumnasaraf/OctoUser pull request #8
Opened 2022-08-15 09:45 UTC by deeproop

Closes #3 

## 👨‍💻 Changes proposed

Added the project working - 

- For the desired username entered information is fetched through Github API ( JavaScript fetch("URL") function is used ).
- Validity of user is checked.
- Then Data is converted to JSON and then filtered out.
- Customised JavaScript function is used to generate the output.

2022-08-17 04:06 UTC, Pradumnasaraf requested changes
Thank you for the PR, please fix the typo

2022-08-17 04:06 UTC, Pradumnasaraf commented on README.md
> +## Project Working1
```suggestion
## Project Working
```

2022-08-17 05:12 UTC, deeproop commented
Typo Fixed 👍

2022-08-18 17:26 UTC, SamiShaikh6810 approved these changes

2022-08-19 18:02 UTC, Pradumnasaraf approved these changes
Looks good merge!

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-08-19 18:03 UTC, merged